apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: jenkins
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - name: http
    port: 8060
    targetPort: 8060
    protocol: TCP
  type: ClusterIP