version: 0.2
batch:
  fast-fail: false
  build-list:
    - identifier: configserver
      buildspec: configserver/buildspec.yml
    # - identifier: order
    #   buildspec: service-order/buildspec.yml
    # - identifier: payment
    #   buildspec: service-payment/buildspec.yml
