version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies"

  pre_build:
    commands:
      - echo "Starting pre-build tasks"

  build:
    commands:
      - echo "Building configserver"
      - cd configserver
      - mvn clean install -DskipTests
      - sksjdkf
      - sdfljkds
      - mvn clean test

  post_build:
    commands:
      - echo "Build Completed"
      - echo "Pushing Artifacts"
reports:
  junit-reports:
    files:
      - "**/target/surefire-reports/*.xml"
    base-directory: .
    discard-paths: no
# batch:
#   fast-fail: false
#   build-list:
#     - identifier: configserver
#       buildspec: configserver/buildspec.yml
#     - identifier: order
#       buildspec: service-order/buildspec.yml
#     - identifier: payment
#       buildspec: service-payment/buildspec.yml
