server:
  port: 8787
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: sekhar
    password: sekhar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

