server:
  port: 8040
spring:
  kafka:
    consumer:
      bootstrap-servers: b-2.microservicesecommerce.nmefo7.c8.kafka.us-east-1.amazonaws.com
:9092,b-2.microservicesecommerce.nmefo7.c8.kafka.us-east-1.amazonaws.com
:9092,b-3.microservicesecommerce.nmefo7.c8.kafka.us-east-1.amazonaws.com
:9092

      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.sekhar.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.sekhar.ecommerce.kafka.payment.PaymentConfirmation
  mail:
    host: smtp.gmail.com
    port: 587
    username: sunkarisekhar36@gmail.com
    password: pyabpgelinykqcea
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
