spring:
  application:
     config:
       customer-url: http://localhost:8090/api/v1/customers
       payment-url: http://localhost:8040/api/v1/payments
       product-url: http://localhost:8050/api/v1/products
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: sekhar
    password: sekhar
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
server:
  port: 8070

