spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.c9yig4a82pxl.eu-north-1.rds.amazonaws.com:5432/orders
    username: postgres
    password: Sekharamma123

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true      
    properties:
      hibernate:
        format_sql: true 

  kafka:
    producer:
      bootstrap-servers: b-3.priductapicluster.jbxukd.c4.kafka.eu-north-1.amazonaws.com:9092,b-1.priductapicluster.jbxukd.c4.kafka.eu-north-1.amazonaws.com:9092,b-2.priductapicluster.jbxukd.c4.kafka.eu-north-1.amazonaws.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.sekhar.ecommerce.kafka.OrderConfirmation

server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/auth/users
    payment-url: http://localhost:8040/api/v1/payments
    product-url: http://localhost:8050/api/v1/products
