apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: ecommerce
type: Opaque
data:
  DB_PASSWORD: U2VraGFyYW1tYTEyMw== # Base64 encoded: Sekharamma123
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-secrets
  namespace: ecommerce
type: Opaque
data:
  MAIL_PASSWORD: cHlhYnBnZWxpbnlrcWNlYQ== # Base64 encoded: pyabpgelinykqcea