spring:
  profiles:
    active: native
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: health, info   # expose health & info endpoints
  endpoint:
    health:
      show-details: always      # show detailed health info
