apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: ecommerce
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
  - name: http
    port: 8222
    targetPort: 8222
    protocol: TCP
  type: ClusterIP