apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientcode-deployment
  namespace: jenkins
  labels:
    app: clientcode
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: clientcode
  template:
    metadata:
      labels:
        app: clientcode
    spec:
      # nodeSelector:
      #    agentpool: amdpool
      containers:
      - name: clientcode
        image: sunkarisomasekhar/client-svc:v4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
     
        # env:
        # - name: VITE_API_BASE_URL
        #   value: "http://gateway-service:8222"
        # - name: NGINX_PORT
        #   value: "80"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
      restartPolicy: Always

      # imagePullSecrets:
      #   - name: ecr-clientcode-secret
