apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientcode-deployment
  namespace: ecommerce
  labels:
    app: clientcode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientcode
  template:
    metadata:
      labels:
        app: clientcode
    spec:
      containers:
      - name: clientcode
        image: 068856380156.dkr.ecr.us-east-1.amazonaws.com/client-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "http://gateway-service:8222"
        - name: NGINX_PORT
          value: "80"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10