apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: clientcode-hpa
  namespace: jenkins
  labels:
    app: clientcode
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clientcode-deployment
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30