apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: ecommerce
  labels:
    app: customer-service
spec:
  selector:
    app: customer-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP