apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: jenkins
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
  - name: http
    port: 8050
    targetPort: 8050
    protocol: TCP
  type: ClusterIP