apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  namespace: ecommerce
  labels:
    app: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
      - name: discovery
        image: 068856380156.dkr.ecr.us-east-1.amazonaws.com/discovery-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: service-urls
              key: CONFIG_SERVER_URL
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "discovery-service"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://discovery-service:8761/eureka/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
      imagePullSecrets:
        - name: ecr-registry-secret