apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: ecommerce
  labels:
    app: discovery
spec:
  selector:
    app: discovery
  ports:
  - name: http
    port: 8761
    targetPort: 8761
    protocol: TCP
  type: ClusterIP